# Generated by Django 5.1 on 2025-02-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("investment_chat_app", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="SECFilings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("form_type", models.CharField(max_length=10)),
                ("filing_date", models.DateField()),
                ("path_to_doc", models.URLField()),
            ],
        )
    ]
