# Generated by Django 5.1 on 2025-04-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("investment_chat_app", "0002_secfilings")]

    operations = [
        migrations.AlterField(
            model_name="secfilings",
            name="ticker",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="secfilings", unique_together={("ticker", "filing_date")}
        ),
    ]
